// ============================================================
// CONFIGURATION — Edit this file to customize the quiz game
// ============================================================

const CONFIG = {
  courseName: "Econ 111",
  courseTitle: "Principles of Microeconomics",
  university: "SMU",
  instructor: "Aljoscha Janssen",

  // Currently active week (students can play weeks 1 through this number)
  currentWeek: 3,

  // Quiz settings
  quizDuration: 30 * 60, // 30 minutes in seconds
  questionsPerQuiz: 15,
  allowRetakes: false, // one attempt per week per student
  adminEmails: ["ajanssen@smu.edu.sg"], // these emails can retake quizzes indefinitely

  // Approved student emails (lowercase). Set requireApprovedEmail = true to enforce.
  requireApprovedEmail: true,
  approvedEmails: [
    "ajanssen@smu.edu.sg",
    "denise.seah.2025@economics.smu.edu.sg",
    "soniar.2022@business.smu.edu.sg",
    "lisa.tan.2025@economics.smu.edu.sg",
    "md.canvu.2025@economics.smu.edu.sg",
    "ezekiel.ho.2025@economics.smu.edu.sg",
    "sm.sia.2025@economics.smu.edu.sg",
    "claire.lee.2024@socsc.smu.edu.sg",
    "kaiyi.kho.2025@economics.smu.edu.sg",
    "glenn.poon.2025@economics.smu.edu.sg",
    "maximus.ee.2025@economics.smu.edu.sg",
    "pranay.pk.2025@economics.smu.edu.sg",
    "siddharth.j.2025@economics.smu.edu.sg",
    "suanyin.foo.2025@economics.smu.edu.sg",
    "szehan.lim.2024@business.smu.edu.sg",
    "kethanv.s.2025@economics.smu.edu.sg",
    "andria.koh.2025@economics.smu.edu.sg",
    "ee.john.2024@socsc.smu.edu.sg",
    "dron.a.2025@economics.smu.edu.sg",
    "junyong.low.2025@economics.smu.edu.sg",
    "jamie.liaw.2025@cis.smu.edu.sg",
    "kareenderbs.2025@economics.smu.edu.sg",
    "karti.liau.2025@economics.smu.edu.sg",
    "manveers.b.2025@economics.smu.edu.sg",
    "nikitha.l.2025@economics.smu.edu.sg",
    "wanghon.lam.2024@economics.smu.edu.sg",
    "harith.h.2025@economics.smu.edu.sg",
    "dylan.fang.2025@economics.smu.edu.sg",
    "alexander.l.2025@economics.smu.edu.sg",
    "mazzel.koh.2025@economics.smu.edu.sg",
    "joanna.yeo.2025@economics.smu.edu.sg",
    "tanay.s.2025@economics.smu.edu.sg",
    "maia.goh.2025@economics.smu.edu.sg",
    "mandy.low.2024@economics.smu.edu.sg",
    "ritisha.s.2025@economics.smu.edu.sg",
    "reagan.yeo.2024@economics.smu.edu.sg",
    "darrenchiam.2025@economics.smu.edu.sg",
    "hiral.n.2025@economics.smu.edu.sg",
    "jinging.tan.2025@economics.smu.edu.sg",
    "julian.toh.2025@economics.smu.edu.sg",
    "yewjun.lim.2025@economics.smu.edu.sg",
    "samuel.ong.2025@economics.smu.edu.sg",
    "elias.wong.2025@economics.smu.edu.sg",
    "vedang.k.2025@economics.smu.edu.sg",
    "zhongxin.w.2025@economics.smu.edu.sg",
    "tecklee.ong.2025@economics.smu.edu.sg",
    "yk.goh.2025@economics.smu.edu.sg",
    "teresa.teo.2025@economics.smu.edu.sg",
    "junzhe.zhao.2025@economics.smu.edu.sg",
    "damian.chua.2025@economics.smu.edu.sg",
    "jasperyrjas.2025@exchange.smu.edu.sg",
    "ezekiel.tan.2025@economics.smu.edu.sg",
    "xuanyu.lyu.2025@economics.smu.edu.sg",
    "zijun.goay.2025@economics.smu.edu.sg",
    "darshika.j.2025@economics.smu.edu.sg",
    "keane.lim.2025@economics.smu.edu.sg",
    "matthew.low.2025@economics.smu.edu.sg",
    "hs.tang.2024@cis.smu.edu.sg",
    "chloee.mak.2025@economics.smu.edu.sg",
    "sy.leong.2025@economics.smu.edu.sg",
    "keyushh.t.2025@economics.smu.edu.sg",
    "evan.teo.2025@economics.smu.edu.sg",
    "shu.wu.2025@economics.smu.edu.sg",
    "s.feodoroff.2025@exchange.smu.edu.sg",
    "nathaniel.l.2025@economics.smu.edu.sg",
    "goutham.k.2025@economics.smu.edu.sg",
    "mfaris.k.2025@economics.smu.edu.sg",
    "lx.cross.2024@socsc.smu.edu.sg",
    "tinghui.toh.2025@economics.smu.edu.sg",
    "giselletang.2025@economics.smu.edu.sg",
    "jw.yeoh.2025@cis.smu.edu.sg",
    "twj.lo.2024@business.smu.edu.sg",
    "songwen.qiu.2025@economics.smu.edu.sg",
    "darrell.soh.2025@economics.smu.edu.sg",
    "kenneth.lim.2025@economics.smu.edu.sg",
    "joshua.tjen.2025@economics.smu.edu.sg",
    "t.reaz.2024@socsc.smu.edu.sg",
    "jiayi.liu.2025@economics.smu.edu.sg",
    "weihan.chen.2025@economics.smu.edu.sg",
    "twishac.r.2025@economics.smu.edu.sg",
    "shaun.liu.2025@economics.smu.edu.sg",
    "wenxin.l.2025@economics.smu.edu.sg",
    "zakarya.z.2025@economics.smu.edu.sg",
    "ethan.t.2025@economics.smu.edu.sg",
    "siya.c.2025@economics.smu.edu.sg",
    "sean.sim.2024@economics.smu.edu.sg",
    "adam.szwed.2025@exchange.smu.edu.sg",
    "roshan.h.2024@economics.smu.edu.sg",
    "priyanjali.2025@economics.smu.edu.sg",
    "ahaan.gupta.2025@economics.smu.edu.sg",
    "crystal.lim.2025@economics.smu.edu.sg",
  ],

  // Google Sheets API for shared leaderboard (free, no billing required)
  // Deploy the Apps Script as a web app and paste the URL here.
  sheetsApiUrl: "https://script.google.com/macros/s/AKfycbwfSLX6hblTqQGrpLgtZB4-5Z_9BRpwWDYG6xF0_NRlh31jaNZuTVHIP9nWSXzC2GtmPw/exec",
};
